Feature: CMA

  Scenario Outline: Verify CMA page is displayed for HCA consultants
    Given user opens URL
    And click search for a consultant
    And user fill the form from sheetname "<sheetName>" and rownumber <rowNumber>
    And click next button
    And click Here hyperlink
    Then a new page is opened with the doctor name
    And page title should be CMA Disclosure | How we work with doctors | HCA UK

    Examples: 
      | sheetName | rowNumber |
      | Doctors   |         1 |
      | Doctors   |         2 |
      | Doctors   |         3 |
      | Doctors   |         4 |
      | Doctors   |         5 |
      | Doctors   |         6 |
      | Doctors   |         7 |
      | Doctors   |         8 |
      | Doctors   |         9 |
      | Doctors   |        10 |
      | Doctors   |        11 |
      | Doctors   |        12 |
      | Doctors   |        13 |
      | Doctors   |        14 |
      | Doctors   |        15 |
      | Doctors   |        16 |
      | Doctors   |        17 |
      | Doctors   |        18 |
      | Doctors   |        19 |
      | Doctors   |        20 |
      | Doctors   |        21 |
      | Doctors   |        22 |
      | Doctors   |        23 |
      | Doctors   |        24 |
      | Doctors   |        25 |
      | Doctors   |        26 |
      | Doctors   |        27 |
      | Doctors   |        28 |
      | Doctors   |        29 |
      | Doctors   |        30 |
      | Doctors   |        31 |
      | Doctors   |        32 |
      | Doctors   |        33 |
      | Doctors   |        34 |
      | Doctors   |        35 |
      | Doctors   |        36 |
      | Doctors   |        37 |
      | Doctors   |        38 |
      | Doctors   |        39 |
      | Doctors   |        40 |
      | Doctors   |        41 |
      | Doctors   |        42 |
      | Doctors   |        43 |
      | Doctors   |        44 |
      | Doctors   |        45 |
      | Doctors   |        46 |
      | Doctors   |        47 |
      | Doctors   |        48 |
      | Doctors   |        49 |
      | Doctors   |        50 |
      | Doctors   |        51 |
      | Doctors   |        52 |
      | Doctors   |        53 |
      | Doctors   |        54 |
      | Doctors   |        55 |
      | Doctors   |        56 |
      | Doctors   |        57 |
      | Doctors   |        58 |
      | Doctors   |        59 |
      | Doctors   |        60 |
      | Doctors   |        61 |
      | Doctors   |        62 |
      | Doctors   |        63 |
      | Doctors   |        64 |
      | Doctors   |        65 |
      | Doctors   |        66 |
      | Doctors   |        67 |
      | Doctors   |        68 |
      | Doctors   |        69 |
      | Doctors   |        70 |
      | Doctors   |        71 |
      | Doctors   |        72 |
      | Doctors   |        73 |
      | Doctors   |        74 |
      | Doctors   |        75 |
      | Doctors   |        76 |
      | Doctors   |        77 |
      | Doctors   |        78 |
      | Doctors   |        79 |
      | Doctors   |        80 |
      | Doctors   |        81 |
      | Doctors   |        82 |
      | Doctors   |        83 |
      | Doctors   |        84 |
      | Doctors   |        85 |
      | Doctors   |        86 |
      | Doctors   |        87 |
      | Doctors   |        88 |
      | Doctors   |        89 |
      | Doctors   |        90 |
      | Doctors   |        91 |
      | Doctors   |        92 |
      | Doctors   |        93 |
      | Doctors   |        94 |
      | Doctors   |        95 |
      | Doctors   |        96 |
      | Doctors   |        97 |
      | Doctors   |        98 |
      | Doctors   |        99 |
      | Doctors   |       100 |
      | Doctors   |       101 |
      | Doctors   |       102 |
      | Doctors   |       103 |
      | Doctors   |       104 |
      | Doctors   |       105 |
      | Doctors   |       106 |
      | Doctors   |       107 |
      | Doctors   |       108 |
      | Doctors   |       109 |
      | Doctors   |       110 |
      | Doctors   |       111 |
      | Doctors   |       112 |
      | Doctors   |       113 |
      | Doctors   |       114 |
      | Doctors   |       115 |
      | Doctors   |       116 |
      | Doctors   |       117 |
      | Doctors   |       118 |
      | Doctors   |       119 |
      | Doctors   |       120 |
      | Doctors   |       121 |
      | Doctors   |       122 |
      | Doctors   |       123 |
      | Doctors   |       124 |
      | Doctors   |       125 |
      | Doctors   |       126 |
      | Doctors   |       127 |
      | Doctors   |       128 |
      | Doctors   |       129 |
      | Doctors   |       130 |
      | Doctors   |       131 |
      | Doctors   |       132 |
      | Doctors   |       133 |
      | Doctors   |       134 |
      | Doctors   |       135 |
      | Doctors   |       136 |
      | Doctors   |       137 |
      | Doctors   |       138 |
      | Doctors   |       139 |
      | Doctors   |       140 |
      | Doctors   |       141 |
      | Doctors   |       142 |
      #| Doctors   |       143 |
      #| Doctors   |       144 |
      #| Doctors   |       145 |
      #| Doctors   |       146 |
      #| Doctors   |       147 |
      #| Doctors   |       148 |
      #| Doctors   |       149 |
