Feature: Check new consultants are correctly added

  Scenario Outline: Verify new consultant has been added to finder
    Given user navigates to finder page
    And user accept cookies
    And click search for a consultant
    And I fill the form from sheetname "<sheetName>" and rownumber <rowNumber>
    And user click next tab
    And user click Book online
    #When user click appointment type
    When user click initial appt
    And user select a location
    Then weekdays header should be displayed
    And user click appointment link
    And user select follow on appt
    And user select a location
    Then weekdays header should be displayed

    Examples: 
      | sheetName | rowNumber |
      | Doctors   |         1 |
      | Doctors   |         2 |
      | Doctors   |         3 |
      | Doctors   |         4 |
      | Doctors   |         5 |
      | Doctors   |         6 |
      | Doctors   |         7 |
      | Doctors   |         8 |
      | Doctors   |         9 |
      | Doctors   |        10 |
      | Doctors   |        11 |
      | Doctors   |        12 |
      | Doctors   |        13 |
      | Doctors   |        14 |
      | Doctors   |        15 |
      | Doctors   |        16 |
      | Doctors   |        17 |
      | Doctors   |        18 |
      | Doctors   |        19 |
      | Doctors   |        20 |
      | Doctors   |        21 |
      | Doctors   |        22 |
      | Doctors   |        23 |
      | Doctors   |        24 |
      | Doctors   |        25 |
      | Doctors   |        26 |
      | Doctors   |        27 |
      | Doctors   |        28 |
      | Doctors   |        29 |
      | Doctors   |        30 |
      | Doctors   |        31 |
      | Doctors   |        32 |
      | Doctors   |        33 |
      | Doctors   |        34 |
      | Doctors   |        35 |
      | Doctors   |        36 |
      | Doctors   |        37 |
      | Doctors   |        38 |
      | Doctors   |        39 |
      | Doctors   |        40 |
      | Doctors   |        41 |
      | Doctors   |        42 |
      | Doctors   |        43 |
      | Doctors   |        44 |
      | Doctors   |        45 |
      | Doctors   |        46 |
      | Doctors   |        47 |
      | Doctors   |        48 |
      | Doctors   |        49 |
      | Doctors   |        50 |
      | Doctors   |        51 |
      | Doctors   |        52 |
      | Doctors   |        53 |
      | Doctors   |        54 |
      | Doctors   |        55 |
      | Doctors   |        56 |
      | Doctors   |        57 |
      | Doctors   |        58 |
      | Doctors   |        59 |
      | Doctors   |        60 |
      | Doctors   |        61 |
      | Doctors   |        62 |
      | Doctors   |        63 |
      | Doctors   |        64 |
      | Doctors   |        65 |
      | Doctors   |        66 |
      | Doctors   |        67 |
      | Doctors   |        68 |
      | Doctors   |        69 |
      | Doctors   |        70 |
      | Doctors   |        71 |
      | Doctors   |        72 |
      | Doctors   |        73 |
      | Doctors   |        74 |
      | Doctors   |        75 |
      | Doctors   |        76 |
      | Doctors   |        77 |
      | Doctors   |        78 |
      | Doctors   |        79 |
      | Doctors   |        80 |
      | Doctors   |        81 |
      | Doctors   |        82 |
      | Doctors   |        83 |
      | Doctors   |        84 |
      | Doctors   |        85 |
      | Doctors   |        86 |
      | Doctors   |        87 |
      | Doctors   |        88 |
      | Doctors   |        89 |
      | Doctors   |        90 |
      | Doctors   |        91 |
      | Doctors   |        92 |
      | Doctors   |        93 |
      | Doctors   |        94 |
      | Doctors   |        95 |
      | Doctors   |        96 |
      | Doctors   |        97 |
      | Doctors   |        98 |
      | Doctors   |        99 |
      | Doctors   |       100 |
      | Doctors   |       101 |
      | Doctors   |       102 |
      | Doctors   |       103 |
      | Doctors   |       104 |
      | Doctors   |       105 |
      | Doctors   |       106 |
      | Doctors   |       107 |
      | Doctors   |       108 |
      | Doctors   |       109 |
      | Doctors   |       110 |
      | Doctors   |       111 |
      | Doctors   |       112 |
      | Doctors   |       113 |
      | Doctors   |       114 |
      | Doctors   |       115 |
      | Doctors   |       116 |
      | Doctors   |       117 |
      | Doctors   |       118 |
      | Doctors   |       119 |
      | Doctors   |       120 |
      | Doctors   |       121 |
      | Doctors   |       122 |
      | Doctors   |       123 |
      | Doctors   |       124 |
      | Doctors   |       125 |
      | Doctors   |       126 |
      | Doctors   |       127 |
      | Doctors   |       128 |
      | Doctors   |       129 |
      | Doctors   |       130 |
      | Doctors   |       131 |
      | Doctors   |       132 |
      | Doctors   |       133 |
      | Doctors   |       134 |
      | Doctors   |       135 |
      | Doctors   |       136 |
      | Doctors   |       137 |
      | Doctors   |       138 |
      | Doctors   |       139 |
      | Doctors   |       140 |
      | Doctors   |       141 |
      | Doctors   |       142 |
      | Doctors   |       143 |
      | Doctors   |       144 |
      | Doctors   |       145 |
      | Doctors   |       146 |
      | Doctors   |       147 |
      | Doctors   |       148 |
      | Doctors   |       149 |
      | Doctors   |       150 |
      | Doctors   |       151 |
      | Doctors   |       152 |
      | Doctors   |       153 |
      | Doctors   |       154 |
      | Doctors   |       155 |
      | Doctors   |       156 |
      | Doctors   |       157 |
      | Doctors   |       158 |
      | Doctors   |       159 |
      | Doctors   |       160 |
      | Doctors   |       161 |
      | Doctors   |       162 |
      | Doctors   |       163 |
      | Doctors   |       164 |
      | Doctors   |       165 |
      | Doctors   |       166 |
      | Doctors   |       167 |
      | Doctors   |       168 |
      | Doctors   |       169 |
      | Doctors   |       170 |
      | Doctors   |       171 |
      | Doctors   |       172 |
      | Doctors   |       173 |
      | Doctors   |       174 |
      | Doctors   |       175 |
      | Doctors   |       176 |
      | Doctors   |       177 |
      | Doctors   |       178 |
      | Doctors   |       179 |
      | Doctors   |       180 |
      | Doctors   |       181 |
      | Doctors   |       182 |
      | Doctors   |       183 |
      | Doctors   |       184 |
      | Doctors   |       185 |
      | Doctors   |       186 |
      | Doctors   |       187 |
      | Doctors   |       188 |
      | Doctors   |       189 |
      | Doctors   |       190 |
      | Doctors   |       191 |
      | Doctors   |       192 |
      | Doctors   |       193 |
      | Doctors   |       194 |
      | Doctors   |       195 |
      | Doctors   |       196 |
      | Doctors   |       197 |
      | Doctors   |       198 |
      | Doctors   |       199 |
      | Doctors   |       200 |
      | Doctors   |       201 |
      | Doctors   |       202 |
      | Doctors   |       203 |
      | Doctors   |       204 |
      | Doctors   |       205 |
      | Doctors   |       206 |
      | Doctors   |       207 |
      | Doctors   |       208 |
      | Doctors   |       209 |
      | Doctors   |       210 |
      | Doctors   |       211 |
      | Doctors   |       212 |
      | Doctors   |       213 |
      | Doctors   |       214 |
      | Doctors   |       215 |
      | Doctors   |       216 |
      | Doctors   |       217 |
      | Doctors   |       218 |
      | Doctors   |       219 |
      | Doctors   |       220 |
      | Doctors   |       221 |
      | Doctors   |       222 |
      | Doctors   |       223 |
      | Doctors   |       224 |
      | Doctors   |       225 |
      | Doctors   |       226 |
      | Doctors   |       227 |
      | Doctors   |       228 |
      | Doctors   |       229 |
      | Doctors   |       230 |
      | Doctors   |       231 |
      | Doctors   |       232 |
      | Doctors   |       233 |
      | Doctors   |       234 |
      | Doctors   |       235 |
      | Doctors   |       236 |
      | Doctors   |       237 |
      | Doctors   |       238 |
      | Doctors   |       239 |
      | Doctors   |       240 |
      | Doctors   |       241 |
      | Doctors   |       242 |
      | Doctors   |       243 |
      | Doctors   |       244 |
      | Doctors   |       245 |
      | Doctors   |       246 |
      | Doctors   |       247 |
      | Doctors   |       248 |
      | Doctors   |       249 |
      | Doctors   |       250 |
      | Doctors   |       251 |
      | Doctors   |       252 |
      | Doctors   |       253 |
      | Doctors   |       254 |
      | Doctors   |       255 |
      | Doctors   |       256 |
      | Doctors   |       257 |
      | Doctors   |       258 |
      | Doctors   |       259 |
      | Doctors   |       260 |
      | Doctors   |       261 |
      | Doctors   |       262 |
      | Doctors   |       263 |
      | Doctors   |       264 |
      | Doctors   |       265 |
      | Doctors   |       266 |
      | Doctors   |       267 |
      | Doctors   |       268 |
      | Doctors   |       269 |
      | Doctors   |       270 |
      | Doctors   |       271 |
      | Doctors   |       272 |
      | Doctors   |       273 |
      | Doctors   |       274 |
      | Doctors   |       275 |
      | Doctors   |       276 |
      | Doctors   |       277 |
      | Doctors   |       278 |
      | Doctors   |       279 |
      | Doctors   |       280 |
      | Doctors   |       281 |
      | Doctors   |       282 |
      | Doctors   |       283 |
      | Doctors   |       284 |
      | Doctors   |       285 |
      | Doctors   |       286 |
      | Doctors   |       287 |
      | Doctors   |       288 |
      | Doctors   |       289 |
      | Doctors   |       290 |
      | Doctors   |       291 |
      | Doctors   |       292 |
      | Doctors   |       293 |
      | Doctors   |       294 |
      | Doctors   |       295 |
      | Doctors   |       296 |
      | Doctors   |       297 |
      | Doctors   |       298 |
      | Doctors   |       299 |
      | Doctors   |       300 |
      | Doctors   |       301 |
      | Doctors   |       302 |
      | Doctors   |       303 |
      | Doctors   |       304 |
      | Doctors   |       305 |
      | Doctors   |       306 |
      | Doctors   |       307 |
      | Doctors   |       308 |
      | Doctors   |       309 |
      | Doctors   |       310 |
      | Doctors   |       311 |
      | Doctors   |       312 |
      | Doctors   |       313 |
      | Doctors   |       314 |
      | Doctors   |       315 |
      | Doctors   |       316 |
      | Doctors   |       317 |
      | Doctors   |       318 |
      | Doctors   |       319 |
      | Doctors   |       320 |
      | Doctors   |       321 |
      | Doctors   |       322 |
      | Doctors   |       323 |
      | Doctors   |       324 |
      | Doctors   |       325 |
      | Doctors   |       326 |
      | Doctors   |       327 |
      | Doctors   |       328 |
      | Doctors   |       329 |
      | Doctors   |       330 |
      | Doctors   |       331 |
      | Doctors   |       332 |
      | Doctors   |       333 |
      | Doctors   |       334 |
      | Doctors   |       335 |
      | Doctors   |       336 |
      | Doctors   |       337 |
      | Doctors   |       338 |
      | Doctors   |       339 |
      | Doctors   |       340 |
      | Doctors   |       341 |
      | Doctors   |       342 |
      | Doctors   |       343 |
      | Doctors   |       344 |
      | Doctors   |       345 |
      | Doctors   |       346 |
      | Doctors   |       347 |
      | Doctors   |       348 |
      | Doctors   |       349 |
      | Doctors   |       350 |
      | Doctors   |       351 |
      | Doctors   |       352 |
      | Doctors   |       353 |
      | Doctors   |       354 |
      | Doctors   |       355 |
      | Doctors   |       356 |
      | Doctors   |       357 |
      | Doctors   |       358 |
      | Doctors   |       359 |
      | Doctors   |       360 |
      | Doctors   |       361 |
      | Doctors   |       362 |
      | Doctors   |       363 |
      | Doctors   |       364 |
      | Doctors   |       365 |
      | Doctors   |       366 |
      | Doctors   |       367 |
      | Doctors   |       368 |
      | Doctors   |       369 |
      | Doctors   |       370 |
      | Doctors   |       371 |
      | Doctors   |       372 |
      | Doctors   |       373 |
      | Doctors   |       374 |
      | Doctors   |       375 |
      | Doctors   |       376 |
      | Doctors   |       377 |
      | Doctors   |       378 |
      | Doctors   |       379 |
      | Doctors   |       380 |
      | Doctors   |       381 |
      | Doctors   |       382 |
      | Doctors   |       383 |
      | Doctors   |       384 |
      | Doctors   |       385 |
      | Doctors   |       386 |
      | Doctors   |       387 |
      | Doctors   |       388 |
      | Doctors   |       389 |
      | Doctors   |       390 |
      | Doctors   |       391 |
      | Doctors   |       392 |
      | Doctors   |       393 |
      | Doctors   |       394 |
      | Doctors   |       395 |
      | Doctors   |       396 |
      | Doctors   |       397 |
      | Doctors   |       398 |
      | Doctors   |       399 |
      | Doctors   |       400 |
      | Doctors   |       401 |
      | Doctors   |       402 |
      | Doctors   |       403 |
      | Doctors   |       404 |
      | Doctors   |       405 |
      | Doctors   |       406 |
      | Doctors   |       407 |
      | Doctors   |       408 |
      | Doctors   |       409 |
      | Doctors   |       410 |
      | Doctors   |       411 |
      | Doctors   |       412 |
      | Doctors   |       413 |
      | Doctors   |       414 |
      | Doctors   |       415 |
      | Doctors   |       416 |
      | Doctors   |       417 |
      | Doctors   |       418 |
      | Doctors   |       419 |
      | Doctors   |       420 |
      | Doctors   |       421 |
      | Doctors   |       422 |
      | Doctors   |       423 |
      | Doctors   |       424 |
      | Doctors   |       425 |
      | Doctors   |       426 |
      | Doctors   |       427 |
      | Doctors   |       428 |
      | Doctors   |       429 |
      | Doctors   |       430 |
      | Doctors   |       431 |
      | Doctors   |       432 |
      | Doctors   |       433 |
      | Doctors   |       434 |
      | Doctors   |       435 |
      | Doctors   |       436 |
      | Doctors   |       437 |
      | Doctors   |       438 |
      | Doctors   |       439 |
      | Doctors   |       440 |
      | Doctors   |       441 |
      | Doctors   |       442 |
      | Doctors   |       443 |
      | Doctors   |       444 |
      | Doctors   |       445 |
      | Doctors   |       446 |
      | Doctors   |       447 |
      | Doctors   |       448 |
      | Doctors   |       449 |
      | Doctors   |       450 |
      | Doctors   |       451 |
      | Doctors   |       452 |
      | Doctors   |       453 |
      | Doctors   |       454 |
      | Doctors   |       455 |
      | Doctors   |       456 |
      | Doctors   |       457 |
      | Doctors   |       458 |
      | Doctors   |       459 |
      | Doctors   |       460 |
      | Doctors   |       461 |
      | Doctors   |       462 |
      | Doctors   |       463 |
      | Doctors   |       464 |
      | Doctors   |       465 |
      | Doctors   |       466 |
      | Doctors   |       467 |
      | Doctors   |       468 |
      | Doctors   |       469 |
      | Doctors   |       470 |
      | Doctors   |       471 |
      | Doctors   |       472 |
      | Doctors   |       473 |
      | Doctors   |       474 |
      | Doctors   |       475 |
      | Doctors   |       476 |
      | Doctors   |       477 |
      | Doctors   |       478 |
      | Doctors   |       479 |
      | Doctors   |       480 |
      | Doctors   |       481 |
      | Doctors   |       482 |
      | Doctors   |       483 |
      | Doctors   |       484 |
      | Doctors   |       485 |
      | Doctors   |       486 |
      | Doctors   |       487 |
      | Doctors   |       488 |
      | Doctors   |       489 |
      | Doctors   |       490 |
      | Doctors   |       491 |
      | Doctors   |       492 |
      | Doctors   |       493 |
      | Doctors   |       494 |
      | Doctors   |       495 |
      | Doctors   |       496 |
      | Doctors   |       497 |
      | Doctors   |       498 |
      | Doctors   |       499 |
      | Doctors   |       500 |
      | Doctors   |       501 |
      | Doctors   |       502 |
      | Doctors   |       503 |
      | Doctors   |       504 |
      | Doctors   |       505 |
      | Doctors   |       506 |
      | Doctors   |       507 |
      | Doctors   |       508 |
      | Doctors   |       509 |
      | Doctors   |       510 |
      | Doctors   |       511 |
      | Doctors   |       512 |
      | Doctors   |       513 |
      | Doctors   |       514 |
      | Doctors   |       515 |
      | Doctors   |       516 |
      | Doctors   |       517 |
      | Doctors   |       518 |
      | Doctors   |       519 |
      | Doctors   |       520 |
      | Doctors   |       521 |
      | Doctors   |       522 |
      | Doctors   |       523 |
      | Doctors   |       524 |
      | Doctors   |       525 |
      | Doctors   |       526 |
      | Doctors   |       527 |
      | Doctors   |       528 |
      | Doctors   |       529 |
      | Doctors   |       530 |
      | Doctors   |       531 |
      | Doctors   |       532 |
      | Doctors   |       533 |
      | Doctors   |       534 |
      | Doctors   |       535 |
      | Doctors   |       536 |
      | Doctors   |       537 |
      | Doctors   |       538 |
      | Doctors   |       539 |
      | Doctors   |       540 |
      | Doctors   |       541 |
      | Doctors   |       542 |
      | Doctors   |       543 |
      | Doctors   |       544 |
      | Doctors   |       545 |
      | Doctors   |       546 |
      | Doctors   |       547 |
      | Doctors   |       548 |
      | Doctors   |       549 |
      | Doctors   |       550 |
      | Doctors   |       551 |
      | Doctors   |       552 |
      | Doctors   |       553 |
      | Doctors   |       554 |
      | Doctors   |       555 |
      | Doctors   |       556 |
      | Doctors   |       557 |
      | Doctors   |       558 |
      | Doctors   |       559 |
      | Doctors   |       560 |
      | Doctors   |       561 |
      | Doctors   |       562 |
      | Doctors   |       563 |
      | Doctors   |       564 |
      | Doctors   |       565 |
      | Doctors   |       566 |
      | Doctors   |       567 |
      | Doctors   |       568 |
      | Doctors   |       569 |
      | Doctors   |       570 |
      | Doctors   |       571 |
      | Doctors   |       572 |
      | Doctors   |       573 |
      | Doctors   |       574 |
      | Doctors   |       575 |
      | Doctors   |       576 |
      | Doctors   |       577 |
      | Doctors   |       578 |
      | Doctors   |       579 |
      | Doctors   |       580 |
      | Doctors   |       581 |
      | Doctors   |       582 |
      | Doctors   |       583 |
      | Doctors   |       584 |
      | Doctors   |       585 |
      | Doctors   |       586 |
      | Doctors   |       587 |
      | Doctors   |       588 |
      | Doctors   |       589 |
      | Doctors   |       590 |
      | Doctors   |       591 |
      | Doctors   |       592 |
      | Doctors   |       593 |
      | Doctors   |       595 |
      | Doctors   |       596 |
      | Doctors   |       597 |
      | Doctors   |       598 |
      | Doctors   |       599 |
      | Doctors   |       600 |
      | Doctors   |       601 |
      | Doctors   |       602 |
      | Doctors   |       603 |
      | Doctors   |       604 |
      | Doctors   |       605 |
      | Doctors   |       606 |
      | Doctors   |       607 |
      | Doctors   |       608 |
      | Doctors   |       609 |
      | Doctors   |       610 |
      | Doctors   |       611 |
      | Doctors   |       612 |
      | Doctors   |       613 |
      | Doctors   |       614 |
      | Doctors   |       615 |
      | Doctors   |       616 |
      | Doctors   |       617 |
      | Doctors   |       618 |
      | Doctors   |       619 |
      | Doctors   |       620 |
      | Doctors   |       621 |
      | Doctors   |       622 |
      | Doctors   |       623 |
      | Doctors   |       624 |
      | Doctors   |       625 |
      | Doctors   |       626 |
      | Doctors   |       627 |
      | Doctors   |       628 |
      | Doctors   |       629 |
      | Doctors   |       630 |
      | Doctors   |       631 |
      | Doctors   |       632 |
      | Doctors   |       633 |
      | Doctors   |       634 |
      | Doctors   |       635 |
      | Doctors   |       636 |
      | Doctors   |       637 |
      | Doctors   |       638 |
      | Doctors   |       639 |
      | Doctors   |       640 |
      | Doctors   |       641 |
      | Doctors   |       642 |
      | Doctors   |       643 |
      | Doctors   |       644 |
      | Doctors   |       645 |
      | Doctors   |       646 |
      | Doctors   |       647 |
      | Doctors   |       648 |
      | Doctors   |       649 |
      | Doctors   |       650 |
      | Doctors   |       651 |
      | Doctors   |       652 |
      | Doctors   |       653 |
      | Doctors   |       654 |
      | Doctors   |       655 |
      | Doctors   |       656 |
      | Doctors   |       657 |
      | Doctors   |       658 |
      | Doctors   |       659 |
      | Doctors   |       660 |
      | Doctors   |       661 |
      | Doctors   |       662 |
      | Doctors   |       663 |
